namespace SpriteKind {
    export const dort = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile0`, function (sprite, location) {
    info.changeLifeBy(-1)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite3,
    [img`
        ........................
        ........................
        ........................
        ........................
        ........22..............
        ........22..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.ff..........
        ......ffff.ff...........
        ......fff.fff...........
        ......dddedfded.........
        ......eeeeeeeee.........
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........22..............
        ........22..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.ff..........
        ......ffff.ff...........
        ......fff.fff...........
        ......dddedfded.........
        ......eeeeeeeee.........
        `,img`
        ........................
        ........................
        ........................
        ........................
        .......22...............
        .......222..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.ff..........
        ......ffff.ff...........
        ......fff.fff...........
        ......dddedfded.........
        ......eeeeeeeee.........
        `,img`
        ........................
        ........................
        ........................
        ........................
        ......222...............
        ......2222..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.fff.........
        ......ffff...ff.........
        ......ddf...fff.........
        ......edded.ddded.......
        .......eeee.eeeee.......
        `,img`
        ........................
        ........................
        ........................
        ........22..............
        ........222.............
        ........22..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.fff.........
        ....edffff...ff.........
        ....edff.....fff........
        ....ee.......ddded......
        ....ed.......eeeee......
        `,img`
        ........................
        ........................
        ........................
        ..........22............
        .........222............
        .........2..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.fff.........
        ....edffff...ff.........
        ....edff.....fff........
        ....ee.......ddded......
        ....ed.......eeeee......
        `],
    50,
    true
    )
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite3,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . 1 1 . . . 1 1 1 . . . 1 1 . . 
        1 1 . . . . 1 1 1 . . . . 1 1 . 
        1 . . . . 1 1 1 1 1 . . . . 1 . 
        . . . 1 1 1 1 2 1 1 1 1 . . . . 
        . . . 1 1 1 2 5 2 1 1 1 . . . . 
        . . . 1 1 1 1 2 1 1 1 1 . . . . 
        . . . . . 1 1 1 1 1 . . . . . . 
        1 . . . . . 1 1 1 . . . . . 1 . 
        1 1 . . . . 1 1 1 . . . . 1 1 . 
        . 1 1 . . . . . . . . . 1 1 . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . 1 1 . . . . . . . 1 1 . . . 
        . 1 1 . . . . . . . . . 1 1 . . 
        . 1 . . 1 1 . . . 1 1 . . 1 . . 
        . . . . 1 1 1 1 1 1 1 . . . . . 
        . . . . . 1 1 2 1 1 . . . . . . 
        . . . . . 1 2 5 2 1 . . . . . . 
        . . . . . 1 1 2 1 1 . . . . . . 
        . . . . 1 1 1 1 1 1 1 . . . . . 
        . . . . 1 1 . . . 1 1 . . . . . 
        . . 1 . . . . . . . . . . 1 . . 
        . . 1 1 . . . . . . . . 1 1 . . 
        . . . 1 1 . . . . . . 1 1 . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    50,
    true
    )
    myDart = darts.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . 1 . . . . . . . 
        . . . . . . . 1 1 1 . . . . . . 
        . . . . . . 1 1 5 1 1 . . . . . 
        . . . . . 1 1 5 2 5 1 1 . . . . 
        . . . . . . 1 1 5 1 1 . . . . . 
        . . . . . . . 1 1 1 . . . . . . 
        . . . . . . . . 1 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.dort)
})
controller.down.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite3)
    mySprite3.setImage(img`
        ....................
        ....................
        ....................
        ....................
        ......ffffff........
        .....22222222.......
        .....d18dd81d2......
        .....ffffffff222....
        ......ffffff..22....
        .......ffff....2....
        ......ffffff........
        ...ffffffffffff.....
        ..fffffffffffffff...
        .fff..ffffff...fff..
        ddf...ffffff....fdd.
        dd....ffffff.....dd.
        ......ffffff........
        ......ffffff........
        ......ff..ff........
        ......ff..ff........
        ......ff..ff........
        ......ff..ff........
        ......ff..ff........
        ....dedd..dded......
        ....eeee..eeee......
        ....................
        ....................
        ....................
        ....................
        ....................
        `)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite3,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..............22........
        ........ffff..22........
        .......22222222.........
        .......81dddd2.......d..
        .......ffffff.fffffffdd.
        ........fffffffffffffdd.
        ..........fffffff.......
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        ..........ff.ffff.......
        ...........ff.ffff......
        ...........fff.fff......
        .........dedfdeddd......
        .........eeeeeeeee......
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..............22........
        ........ffff..22........
        .......22222222.........
        .......81dddd2.......d..
        .......ffffff.fffffffdd.
        ........fffffffffffffdd.
        ..........fffffff.......
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        ..........ff.ffff.......
        ...........ff.ffff......
        ...........fff.fff......
        .........dedfdeddd......
        .........eeeeeeeee......
        `,img`
        ........................
        ........................
        ........................
        ........................
        ...............22.......
        ........ffff..222.......
        .......22222222.........
        .......81dddd2.......d..
        .......ffffff.fffffffdd.
        ........fffffffffffffdd.
        ..........fffffff.......
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        ..........ff.ffff.......
        ...........ff.ffff......
        ...........fff.fff......
        .........dedfdeddd......
        .........eeeeeeeee......
        `,img`
        ........................
        ........................
        ........................
        ........................
        ...............222......
        ........ffff..2222......
        .......22222222.........
        .......81dddd2.......d..
        .......ffffff.fffffffdd.
        ........fffffffffffffdd.
        ..........fffffff.......
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        .........fff.ffff.......
        .........ff...ffff......
        .........fff...fdd......
        .......deddd.dedde......
        .......eeeee.eeee.......
        `,img`
        ........................
        ........................
        ........................
        ..............22........
        .............222........
        ........ffff..22........
        .......22222222.........
        .......81dddd2.......d..
        .......ffffff.fffffffdd.
        ........fffffffffffffdd.
        ..........fffffff.......
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        .........fff.ffff.......
        .........ff...ffffde....
        ........fff.....ffde....
        ......deddd.......ee....
        ......eeeee.......de....
        `,img`
        ........................
        ........................
        ........................
        ............22..........
        ............222.........
        ........ffff..2.........
        .......22222222.........
        .......81dddd2.......d..
        .......ffffff.fffffffdd.
        ........fffffffffffffdd.
        ..........fffffff.......
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        ..........ffffff........
        .........fff.ffff.......
        .........ff...ffffde....
        ........fff.....ffde....
        ......deddd.......ee....
        ......eeeee.......de....
        `],
    50,
    true
    )
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite3)
    mySprite3.setImage(img`
        ....................
        ....................
        ....................
        ....................
        ......ffffff........
        .....22222222.......
        .....d18dd81d2......
        .....ffffffff222....
        ......ffffff..22....
        .......ffff....2....
        ......ffffff........
        ...ffffffffffff.....
        ..fffffffffffffff...
        .fff..ffffff...fff..
        ddf...ffffff....fdd.
        dd....ffffff.....dd.
        ......ffffff........
        ......ffffff........
        ......ff..ff........
        ......ff..ff........
        ......ff..ff........
        ......ff..ff........
        ......ff..ff........
        ....dedd..dded......
        ....eeee..eeee......
        ....................
        ....................
        ....................
        ....................
        ....................
        `)
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite3)
    mySprite3.setImage(img`
        ....................
        ....................
        ....................
        ....................
        ......ffffff........
        .....22222222.......
        .....d18dd81d2......
        .....ffffffff222....
        ......ffffff..22....
        .......ffff....2....
        ......ffffff........
        ...ffffffffffff.....
        ..fffffffffffffff...
        .fff..ffffff...fff..
        ddf...ffffff....fdd.
        dd....ffffff.....dd.
        ......ffffff........
        ......ffffff........
        ......ff..ff........
        ......ff..ff........
        ......ff..ff........
        ......ff..ff........
        ......ff..ff........
        ....dedd..dded......
        ....eeee..eeee......
        ....................
        ....................
        ....................
        ....................
        ....................
        `)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite3,
    [img`
        ........................
        ........................
        ........................
        ........................
        ........22..............
        ........22..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.ff..........
        ......ffff.ff...........
        ......fff.fff...........
        ......dddedfded.........
        ......eeeeeeeee.........
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........22..............
        ........22..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.ff..........
        ......ffff.ff...........
        ......fff.fff...........
        ......dddedfded.........
        ......eeeeeeeee.........
        `,img`
        ........................
        ........................
        ........................
        ........................
        .......22...............
        .......222..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.ff..........
        ......ffff.ff...........
        ......fff.fff...........
        ......dddedfded.........
        ......eeeeeeeee.........
        `,img`
        ........................
        ........................
        ........................
        ........................
        ......222...............
        ......2222..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.fff.........
        ......ffff...ff.........
        ......ddf...fff.........
        ......edded.ddded.......
        .......eeee.eeeee.......
        `,img`
        ........................
        ........................
        ........................
        ........22..............
        ........222.............
        ........22..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.fff.........
        ....edffff...ff.........
        ....edff.....fff........
        ....ee.......ddded......
        ....ed.......eeeee......
        `,img`
        ........................
        ........................
        ........................
        ..........22............
        .........222............
        .........2..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.fff.........
        ....edffff...ff.........
        ....edff.....fff........
        ....ee.......ddded......
        ....ed.......eeeee......
        `],
    50,
    true
    )
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite3,
    [img`
        ........................
        ........................
        ........................
        ........................
        ........22..............
        ........22..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.ff..........
        ......ffff.ff...........
        ......fff.fff...........
        ......dddedfded.........
        ......eeeeeeeee.........
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........22..............
        ........22..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.ff..........
        ......ffff.ff...........
        ......fff.fff...........
        ......dddedfded.........
        ......eeeeeeeee.........
        `,img`
        ........................
        ........................
        ........................
        ........................
        .......22...............
        .......222..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.ff..........
        ......ffff.ff...........
        ......fff.fff...........
        ......dddedfded.........
        ......eeeeeeeee.........
        `,img`
        ........................
        ........................
        ........................
        ........................
        ......222...............
        ......2222..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.fff.........
        ......ffff...ff.........
        ......ddf...fff.........
        ......edded.ddded.......
        .......eeee.eeeee.......
        `,img`
        ........................
        ........................
        ........................
        ........22..............
        ........222.............
        ........22..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.fff.........
        ....edffff...ff.........
        ....edff.....fff........
        ....ee.......ddded......
        ....ed.......eeeee......
        `,img`
        ........................
        ........................
        ........................
        ..........22............
        .........222............
        .........2..ffff........
        .........22222222.......
        ..d.......2dddd18.......
        .ddfffffff.ffffff.......
        .ddfffffffffffff........
        .......fffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        ........ffffff..........
        .......ffff.fff.........
        ....edffff...ff.........
        ....edff.....fff........
        ....ee.......ddded......
        ....ed.......eeeee......
        `],
    50,
    true
    )
})
let myDart: Dart = null
let ggg: Sprite = null
let mySprite3: Sprite = null
mySprite3 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ......ffffff........
    .....22222222.......
    .....d18dd81d2......
    .....ffffffff222....
    ......ffffff..22....
    .......ffff....2....
    ......ffffff........
    ...ffffffffffff.....
    ..fffffffffffffff...
    .fff..ffffff...fff..
    ddf...ffffff....fdd.
    dd....ffffff.....dd.
    ......ffffff........
    ......ffffff........
    ......ff..ff........
    ......ff..ff........
    ......ff..ff........
    ......ff..ff........
    ......ff..ff........
    ....dedd..dded......
    ....eeee..eeee......
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
controller.moveSprite(mySprite3)
scene.cameraFollowSprite(mySprite3)
scene.setBackgroundImage(img`
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    `)
tiles.setCurrentTilemap(tilemap`level2`)
info.setLife(5)
for (let value of tiles.getTilesByType(assets.tile`myTile0`)) {
    ggg = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . 7 7 . . . . 
        . . . . . . 7 7 7 7 7 7 . . . . 
        . . . . 7 7 7 7 7 7 7 7 . . . . 
        . . . . 1 f 7 7 7 7 7 f 1 . . . 
        . . . 7 7 7 7 7 7 7 7 7 7 7 7 . 
        . . 7 7 7 7 . 7 . 7 7 7 7 7 7 . 
        . . 7 7 7 . 7 . . . 7 7 7 7 7 . 
        7 7 7 7 7 7 . . . . . 7 7 7 7 . 
        7 7 7 7 7 7 7 7 . 7 7 7 7 7 7 . 
        7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
        `, SpriteKind.Enemy)
    tiles.placeOnTile(ggg, value)
}
