name: MakeCode Arcade Release

on: 
  release:
    types:
      - created
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: install node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install makecode
        run: |
          npm install -g pxt
          pxt target arcade
      - name: build js
        run: |
          pxt clean
          pxt install
          pxt build --cloud
      - name: build D51
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw samd51
          pxt build --hw samd51 --cloud
          cp ./built/binary.uf2 binary-d51.uf2
      - name: build F4
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw stm32f401
          pxt build --hw stm32f401 --cloud
          cp ./built/binary.uf2 binary-f4.uf2
      - name: build P0
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw rpi
          pxt build --hw rpi --cloud
          cp ./built/binary.uf2 binary-p0.uf2
      - name: bundle all
        run: |
          cat binary-*.uf2 > built/arcade.uf2
      - name: upload bundled
        uses: Shopify/upload-to-release@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./built/arcade.uf2
          name: arcade.uf2
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/octet-stream
